#Should the plugin use a symbol for the currency
#or the name plular/singular
use-symbol: false
symbol: $

currency-name-singular: "dollar"
currency-name-plural: "dollars"

formatting:
  thousand: "k"
  million: "M"
  billion: "B"
  trillion: "T"
  quadrillion: "Q"
  quintillion: "Qi"

#Should it filter out warnings
#From skins not loading
#WARNING: if enabled could filter out useful errors
suppress-warnings: true

#The maximum amount of transactions saved per player
# Recommended: 20-150
max-history: 100

#Per how many seconds should the
#Data be saved
autosave: 30

#The amount of money for the player to start with
start-amount: 50
