name: FepEconomy
version: '2.2'

main: Fepbox.FepEconomy.FepEconomy
api-version: '1.21'

load: STARTUP

authors: [ _F0to ]
depend: [ Vault ]

libraries:
  - org.xerial:sqlite-jdbc:3.45.3.0

commands:
  bal:
    aliases:
      - balance
  pay:
  togglepay:
    aliases:
      - paytoggle
  payhistory:
  baltop:

permissions:
  fepeconomy.admin:
    default: op
  fepeconomy.baltop.exempt:
    default: op